application: wbor-brunswick
version: 1-3-4
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /index\.html
  script: main.py
- url: /static
  static_dir: static
- url: /dj.*
  script: dj.py
- url: /blog/.*/edit/?
  script: dj.py
- url: /.*
  script: main.py
