application: wbor-hr
version: 1-8-rc2
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "7d"

builtins:
- remote_api: on

handlers:
- url: /
  script: main.app
- url: /index\.html
  script: main.app
- url: /static
  static_dir: static
- url: /fun/?
  static_files: static/screenclean.swf
  upload: static/screenclean.swf
- url: /favicon\.png
  static_files: static/images/favicon.png
  upload: static/images/favicon\.png
- url: /favicon\.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon\.png
- url: /runtests
  script: test_cases.app
- url: /dj.*
  script: dj.app
- url: /api.*
  script: api.app
- url: /blog/.*/edit/?
  script: dj.app
- url: /.*
  script: main.app

libraries:
- name: django
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?static/less/.*
- ^(.*/)?static/docs/.*
- ^(.*/)?README\.md
- ^(.*/)?Makefile
- ^(.*/)?LICENSE
